### PR TITLE
Added guide for ollama/LiteLLM

### PR DESCRIPTION
**Pull request by dwinkler1**

### CODE REVIEW

**Comment by alondmnt** [comment]
Thank you very much!
Will just run a quick test on my laptop and then merge it.

**Comment by danielw2904** [comment]
Perfect. Let me know if something is unclear. I think it would be cool to spawn the two processes directly from Joplin but I have no idea how to implement that (I don't know JavaScript at all unfortunately).

**Comment by Hegghammer** [comment]
I implemented this with ollama/mistral and it works beautifully. Only thing is that the plugin forces me to enter an OpenAI API key even though my setup calls no OpenAI services. Presumably it's a hardcoded check of some sort that can be removed.

**Comment by alondmnt** [comment]
Sorry for the wait, finally got to testing it, and it works great. Thank you!

**Comment by alondmnt** [comment]
@Hegghammer true, Jarvis checks that there's some key entered, but you can enter any random string there.

**Pull request merged**
